name: 'Dependency Review'

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    env:
      FIRST_COMMIT_SHA: 4d2c1db7fc447d15c52af268762f8365210a6e3b
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          head-ref: HEAD
          base-ref: "${{ env.FIRST_COMMIT_SHA }}"
          config-file: './.github/dependency-review-config.yml'
